[package]
name = "books"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.5.17"
env_logger = "0.11.5"
log = "0.4.22"
mdbook = "0.4.40"
pulldown-cmark = "0.12.1"
semver = "1.0.23"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
walkdir = "2.5.0"
